/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SecuritiesImport } from './routes/securities'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SecuritiesRoute = SecuritiesImport.update({
  id: '/securities',
  path: '/securities',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/securities': {
      id: '/securities'
      path: '/securities'
      fullPath: '/securities'
      preLoaderRoute: typeof SecuritiesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/securities': typeof SecuritiesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/securities': typeof SecuritiesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/securities': typeof SecuritiesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/securities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/securities'
  id: '__root__' | '/' | '/securities'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecuritiesRoute: typeof SecuritiesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecuritiesRoute: SecuritiesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/securities"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/securities": {
      "filePath": "securities.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
