/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SecuritiesIndexImport } from './routes/securities/index'
import { Route as SecuritiesTickerImport } from './routes/securities/$ticker'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SecuritiesIndexRoute = SecuritiesIndexImport.update({
  id: '/securities/',
  path: '/securities/',
  getParentRoute: () => rootRoute,
} as any)

const SecuritiesTickerRoute = SecuritiesTickerImport.update({
  id: '/securities/$ticker',
  path: '/securities/$ticker',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/securities/$ticker': {
      id: '/securities/$ticker'
      path: '/securities/$ticker'
      fullPath: '/securities/$ticker'
      preLoaderRoute: typeof SecuritiesTickerImport
      parentRoute: typeof rootRoute
    }
    '/securities/': {
      id: '/securities/'
      path: '/securities'
      fullPath: '/securities'
      preLoaderRoute: typeof SecuritiesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/securities/$ticker': typeof SecuritiesTickerRoute
  '/securities': typeof SecuritiesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/securities/$ticker': typeof SecuritiesTickerRoute
  '/securities': typeof SecuritiesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/securities/$ticker': typeof SecuritiesTickerRoute
  '/securities/': typeof SecuritiesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/securities/$ticker' | '/securities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/securities/$ticker' | '/securities'
  id: '__root__' | '/' | '/securities/$ticker' | '/securities/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecuritiesTickerRoute: typeof SecuritiesTickerRoute
  SecuritiesIndexRoute: typeof SecuritiesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecuritiesTickerRoute: SecuritiesTickerRoute,
  SecuritiesIndexRoute: SecuritiesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/securities/$ticker",
        "/securities/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/securities/$ticker": {
      "filePath": "securities/$ticker.tsx"
    },
    "/securities/": {
      "filePath": "securities/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
